### ISSUE TITLE
Possible To Use This For Streaming Desktop?

### ISSUE THREAD

**Issue by ghost** [WindowsNT/ScreenCapture#4]
I understand this is for saving to a specified file, but could it also be used to stream the desktop to another PC?

Thanks

**Comment by WindowsNT** [comment]
Yes. You can use [MFCreateSinkWriterFromURL](https://docs.microsoft.com/en-us/windows/win32/api/mfreadwrite/nf-mfreadwrite-mfcreatesinkwriterfromurl) passing an  IMFByteStream instead of a file url, that way it writes to your buffer instead of a file.

**Comment by ghost** [comment]
> 
> 
> Yes. You can use [MFCreateSinkWriterFromURL](https://docs.microsoft.com/en-us/windows/win32/api/mfreadwrite/nf-mfreadwrite-mfcreatesinkwriterfromurl) passing an IMFByteStream instead of a file url, that way it writes to your buffer instead of a file.

Thanks for your reply! I'd love to use this library, all that's making me hesitate right now is the video being sped up as shown in [another issue](https://github.com/WindowsNT/ScreenCapture/issues/2). Watching and starred this repository.

**Comment by WindowsNT** [comment]
I added an option to specify a capture callback instead of a buffer.
Note however that when using the MP4 transcoded (for streaming) you must set up the required sample description , see 
https://stackoverflow.com/questions/25129263/cant-add-audio-stream-to-mp4-file-using-sinkwriter-from-media-foundation

(setting manually the sample description,  MF_MT_MPEG4_SAMPLE_DESCRIPTION).

For simplicity, the included code uses ASF which does not require such a description.

**Comment by ghost** [comment]
> 
> 
> I added an option to specify a capture callback instead of a buffer.
> Note however that when using the MP4 transcoded (for streaming) you must set up the required sample description , see
> https://stackoverflow.com/questions/25129263/cant-add-audio-stream-to-mp4-file-using-sinkwriter-from-media-foundation
> 
> (setting manually the sample description, MF_MT_MPEG4_SAMPLE_DESCRIPTION).
> 
> For simplicity, the included code uses ASF which does not require such a description.

Sounds good, I'll report back when I attempt to implement it.

**Comment by valinet** [comment]
I don't understand how to use this library for this use case. Can you provide a more detailed example, please?

Specifically, say I use ASF. The way the sample works now, is it creates an ASF file. When you try to open it, subsequent `_wfopen_s` calls fail, because the file is opened in whatever video player you chose. Okay, so if this is not the use case, should I serve the file with an HTTP server? This doesn't work either (I used IIS). I am pretty new to all of this, so I am not familiar with all this stuff, do I instead need to set up a HLS server and have this example connect over a socket to that and throw the bytes at it?

My use case is live streaming the screen of another computer in the LAN (or in the hypervisor's internal network). I managed to do this using Desktop Duplication API + turbo-jpeg in C and serve the converted JPEG frames as an MJPEG stream. It works pretty well, the problem is that decoding multiple streams (I have a use case of 4 concurrent streams) kills the machine that displays them and the videos become choppy. So I thought that using a video codec instead might be the way to go, since that can be efficiently decoded in hardware. I tried to quickly start using this, yet I cannot figure/do not understand how to get something going.

Thank you very much.

**Comment by WindowsNT** [comment]
The sample renders to a file, in order to render to memory you must not save to a file (and try to read the file simultaneously).
Pass an empty string as the 'f' parameter of the DESKTOPCAPTUREPARAMS. Capture.hpp needs some update, it saves the rendering into the "VectorStreamX2 b2" buffer object, so you can instead use a reference to your own VectorStreamX and take the bytes.

**Comment by ghost** [comment]
> 
> 
> I don't understand how to use this library for this use case. Can you provide a more detailed example, please?
> 
> Specifically, say I use ASF. The way the sample works now, is it creates an ASF file. When you try to open it, subsequent `_wfopen_s` calls fail, because the file is opened in whatever video player you chose. Okay, so if this is not the use case, should I serve the file with an HTTP server? This doesn't work either (I used IIS). I am pretty new to all of this, so I am not familiar with all this stuff, do I instead need to set up a HLS server and have this example connect over a socket to that and throw the bytes at it?
> 
> My use case is live streaming the screen of another computer in the LAN (or in the hypervisor's internal network). I managed to do this using Desktop Duplication API + turbo-jpeg in C and serve the converted JPEG frames as an MJPEG stream. It works pretty well, the problem is that decoding multiple streams (I have a use case of 4 concurrent streams) kills the machine that displays them and the videos become choppy. So I thought that using a video codec instead might be the way to go, since that can be efficiently decoded in hardware. I tried to quickly start using this, yet I cannot figure/do not understand how to get something going.
> 
> Thank you very much.

Did you ever find success in using this yet?

**Comment by valinet** [comment]
> > I don't understand how to use this library for this use case. Can you provide a more detailed example, please?
> > Specifically, say I use ASF. The way the sample works now, is it creates an ASF file. When you try to open it, subsequent `_wfopen_s` calls fail, because the file is opened in whatever video player you chose. Okay, so if this is not the use case, should I serve the file with an HTTP server? This doesn't work either (I used IIS). I am pretty new to all of this, so I am not familiar with all this stuff, do I instead need to set up a HLS server and have this example connect over a socket to that and throw the bytes at it?
> > My use case is live streaming the screen of another computer in the LAN (or in the hypervisor's internal network). I managed to do this using Desktop Duplication API + turbo-jpeg in C and serve the converted JPEG frames as an MJPEG stream. It works pretty well, the problem is that decoding multiple streams (I have a use case of 4 concurrent streams) kills the machine that displays them and the videos become choppy. So I thought that using a video codec instead might be the way to go, since that can be efficiently decoded in hardware. I tried to quickly start using this, yet I cannot figure/do not understand how to get something going.
> > Thank you very much.
> 
> Did you ever find success in using this yet?

The project that I was working on that seemed to need this has been postponed indefinitely, so, unfortunately, I did not have the chance to dig more into this.

**Comment by ghost** [comment]
@WindowsNT , do you have any form of contact? I am working on my own project which is similar to this library, and had a few questions. I would be forever grateful if you could.

**Comment by WindowsNT** [comment]
Yes, find me on facebook.
https://www.facebook.com/chourdakismichael

**Comment by valinet** [comment]
But why don’t you share the questions and post the answers here, if they are general. This way, in the spirit of this project, future users may find the information useful or discover answers for similar queries in these replies.
